version: "3.4"
services:
  app-endpoint-server:
    build:
      context: ./app-endpoint-server
      dockerfile: ./Dockerfile
    read_only: true
    volumes:
      - upload:/home/node/upload:ro
      - tmp:/tmp
    ports:
      - 8081:8081
    environment:
      HOME: '/home/node'
  webshell:
    build:
      context: ..
      dockerfile: ./docker/webshell/Dockerfile
    ports:
      - 80:80
    volumes:
      - upload:/upload:rw
volumes:
  upload:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
